#!/usr/bin/env php
<?php

// Enter login
$login = '';

// Enter password
$password = '';

//
$url = 'https://lcab.sms-uslugi.ru/lcabApi/info.php?';

openlog("sms-uslugi", LOG_PID | LOG_PERROR, LOG_LOCAL0);

$params = http_build_query([
    'login'     => $login,
    'password'  => $password
]);

$responce = json_decode(requestHttp($url.$params));

if ($responce->code !== 1) {
    syslog(LOG_ERR, $responce->descr);
} else {
    echo $responce->account;
}

function requestHttp($url, $method = 'POST')
{
    $options = [
        'http' => [
            'method'        => $method,
            'user_agent'    => 'Zabbix Instance (+'.$_SERVER["SERVER_NAME"].')'
        ]
    ];
    $context = stream_context_create($options);
    $data    = file_get_contents($url, false, $context);
    return $data;
}
closelog();